include:
  - project: "moxa/ibg/software/platform/linux/packages/pipeline-template"
    ref: master
    file: "mil1/stretch-standard.yml"

build_deb:
  script:
    - dpkg-buildpackage -us -uc -aarmhf
    - dpkg-buildpackage -us -uc -b
